# download at https://api.cirrus-ci.com/v1/artifact/github/electronstudio/jaylib/main/binary.zip


mac_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
  env:
    RAYLIB_PLATFORM: macosx-arm64
    RAYLIB_VERSION: 5.5.0-3
  setup_script:
    - brew update
    - brew install java11
    - sudo ln -sfn /opt/homebrew/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
    - export CPPFLAGS="-I/opt/homebrew/opt/openjdk@11/include"
  build_raylib_script:
    - git submodule update --init --recursive
    - cd raylib
    - mkdir build
    - cd build
    - cmake -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
    - make -j8
    - sudo make install
  build_script:
    - ./build-java.sh
    - ./build-native.sh
  artifacts:
    path: "./*macos*.jar"

pi_task:
  arm_container:
    image: dtcooper/raspberrypi-os:python-bullseye
  env:
    RAYLIB_PLATFORM: linux-arm64
    RAYLIB_VERSION: 5.5.0-3
  setup_script:
    - apt update
    - apt -y install openjdk-11-jdk cmake libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev libwayland-dev libxkbcommon-dev
  build_raylib_script:
    - git submodule update --init --recursive
    - cd raylib
    - mkdir build
    - cd build
    - cmake -DPLATFORM="Desktop" -DOPENGL_VERSION=2.1 -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
    - make -j2
    - make install
    - find /usr/lib
  build_script:
    - ./build-java.sh
    - ./build-native.sh
  artifacts:
    path: "./*linux*.jar"