name: Build

# Controls when the workflow will run
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  RAYLIB_VERSION: 6.0.0-0

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: electronstudio/ubuntu16-modern:latest
      options: --user root
      volumes:
        # override /__e/node20 because GitHub Actions uses a version that requires too-recent glibc
        - /tmp:/__e/node20

    steps:
      - name: fix node
        run: |
          ln -s /usr/local/bin /__e/node20/bin

      - name: update cmake
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.31.10/cmake-3.31.10-linux-x86_64.tar.gz
          tar xvfz cmake-3.31.10-linux-x86_64.tar.gz
          cp -r cmake-3.31.10-linux-x86_64/* /usr/

      - name: Build SDL
        run: |
          wget https://github.com/libsdl-org/SDL/releases/download/release-3.4.4/SDL3-3.4.4.tar.gz
          tar xvfz SDL3-3.4.4.tar.gz
          sed -i 's/#define SDL_DYNAMIC_API 1/#define SDL_DYNAMIC_API 0/' SDL3-3.4.4/src/dynapi/SDL_dynapi.h
          mkdir build
          cd build
          cmake ../SDL3-3.4.4 -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release -DSDL_DYNAMIC_API=0 -DSDL_VULKAN=OFF -DSDL_CAMERA=OFF -DSDL_GPU=OFF
          cmake --build . --config Release
          cmake --install .

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build raylib
        run: |
          cd raylib
          mkdir build
          cd build
          cmake -DPLATFORM="SDL" -DOPENGL_VERSION="3.3" -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_BUSY_WAIT_LOOP=OFF -DSUPPORT_CUSTOM_FRAME_CONTROL=OFF -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
          make -j2
          make install

      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: linux-x86_64
        run: |
          ./build-java.sh
          ./build-native.sh
          ./build-docs.sh

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jaylib-linux-x86_64
          path: ./jaylib*.jar

  build-linux-32bit:
    runs-on: ubuntu-latest
    container:
      image: electronstudio/ubuntu16-modern:i386
      options: --user root
      volumes:
        # override /__e/node20 because GitHub Actions uses a version that requires too-recent glibc
        - /tmp:/__e/node20

    steps:
      - name: fix node
        run: |
          ln -s /usr/local/bin /__e/node20/bin

      - name: update cmake
        run: |
          wget https://github.com/Kitware/CMake/releases/download/v3.31.10/cmake-3.31.10-linux-x86_64.tar.gz
          tar xvfz cmake-3.31.10-linux-x86_64.tar.gz
          cp -r cmake-3.31.10-linux-x86_64/* /usr/

      - name: Build SDL
        run: |
          wget https://github.com/libsdl-org/SDL/releases/download/release-3.4.4/SDL3-3.4.4.tar.gz
          tar xvfz SDL3-3.4.4.tar.gz
          sed -i 's/#define SDL_DYNAMIC_API 1/#define SDL_DYNAMIC_API 0/' SDL3-3.4.4/src/dynapi/SDL_dynapi.h
          mkdir build
          cd build
          cmake ../SDL3-3.4.4 -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release -DSDL_VULKAN=OFF -DSDL_CAMERA=OFF -DSDL_GPU=OFF
          cmake --build . --config Release
          cmake --install .

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build raylib
        run: |
          cd raylib
          mkdir build
          cd build
          cmake -DPLATFORM="SDL" -DOPENGL_VERSION="Software" -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_BUSY_WAIT_LOOP=OFF -DSUPPORT_CUSTOM_FRAME_CONTROL=OFF -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
          make -j2
          make install

      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: linux-x86
        run: |
          ./build-java.sh
          ./build-native.sh
          ./build-docs.sh

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jaylib-linux-x86
          path: ./jaylib-natives*.jar

  build-linux-arm64:
    runs-on: ubuntu-22.04-arm
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install libs
        run: |
          sudo apt update
          sudo apt -y install cmake libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev libwayland-dev libxkbcommon-dev libgbm-dev libdrm-dev

      - name: Build SDL
        run: |
          wget https://github.com/libsdl-org/SDL/releases/download/release-3.4.4/SDL3-3.4.4.tar.gz
          tar xvfz SDL3-3.4.4.tar.gz
          sed -i 's/#define SDL_DYNAMIC_API 1/#define SDL_DYNAMIC_API 0/' SDL3-3.4.4/src/dynapi/SDL_dynapi.h
          mkdir build
          cd build
          cmake ../SDL3-3.4.4 -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release -DSDL_DYNAMIC_API=0 -DSDL_VULKAN=OFF -DSDL_CAMERA=OFF -DSDL_GPU=OFF
          cmake --build . --config Release
          sudo cmake --install .

      - name: Build raylib with SDL if selected
        run: |
          cd raylib
          mkdir build
          cd build
          cmake -DPLATFORM="SDL" -DOPENGL_VERSION="2.1" -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_BUSY_WAIT_LOOP=OFF -DSUPPORT_CUSTOM_FRAME_CONTROL=OFF -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
          make -j2
          sudo make install

      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: linux-arm64
        run: |
          ./build-java.sh
          ./build-native.sh
          ./build-docs.sh

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jaylib-linux-arm64
          path: ./jaylib-natives*.jar

  build-mac-intel:
    runs-on: macos-15-intel
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.14

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt" # See 'Supported distributions' for available options
          java-version: "8"

      - name: Build SDL
        run: |
          wget https://github.com/libsdl-org/SDL/releases/download/release-3.4.4/SDL3-3.4.4.tar.gz
          tar xvfz SDL3-3.4.4.tar.gz
          sed -i 's/#define SDL_DYNAMIC_API 1/#define SDL_DYNAMIC_API 0/' SDL3-3.4.4/src/dynapi/SDL_dynapi.h
          mkdir build
          cd build
          cmake ../SDL3-3.4.4 -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release -DSDL_DYNAMIC_API=0 -DSDL_VULKAN=OFF -DSDL_CAMERA=OFF -DSDL_GPU=OFF
          cmake --build . --config Release
          cmake --install .

      #  build raylib for arm64 and x86_64 as well
      - name: Build raylib
        run: |
          cd raylib
          mkdir build
          cd build
          cmake -DPLATFORM="SDL" -DOPENGL_VERSION="3.3" DBUILD_EXAMPLES=OFF -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCUSTOMIZE_BUILD=ON -DSUPPORT_BUSY_WAIT_LOOP=OFF -DSUPPORT_CUSTOM_FRAME_CONTROL=OFF -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
          make -j2
          sudo make install

      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: macosx-x86_64
        run: |
          ./build-java.sh
          ./build-native.sh

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jaylib-macosx-x86_64
          path: ./*macosx-x86_64*.jar

  build-mac:
    runs-on: macos-14
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.14

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt" # See 'Supported distributions' for available options
          java-version: "8"

      - name: Build SDL
        run: |
          wget https://github.com/libsdl-org/SDL/releases/download/release-3.4.4/SDL3-3.4.4.tar.gz
          tar xvfz SDL3-3.4.4.tar.gz
          sed -i 's/#define SDL_DYNAMIC_API 1/#define SDL_DYNAMIC_API 0/' SDL3-3.4.4/src/dynapi/SDL_dynapi.h
          mkdir build
          cd build
          cmake ../SDL3-3.4.4 -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_BUILD_TYPE=Release -DSDL_DYNAMIC_API=0 -DSDL_VULKAN=OFF -DSDL_CAMERA=OFF -DSDL_GPU=OFF
          cmake --build . --config Release
          cmake --install .

      #  build raylib for arm64 and x86_64 as well
      - name: Build raylib
        run: |
          cd raylib
          mkdir build
          cd build
          cmake -DPLATFORM="SDL" -DOPENGL_VERSION="3.3" DBUILD_EXAMPLES=OFF -DCMAKE_OSX_ARCHITECTURES="arm64" -DCUSTOMIZE_BUILD=ON -DSUPPORT_BUSY_WAIT_LOOP=OFF -DSUPPORT_CUSTOM_FRAME_CONTROL=OFF -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
          make -j2
          sudo make install

      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: macosx-arm64
        run: |
          ./build-java.sh
          ./build-native.sh

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jaylib-macosx-arm64
          path: ./*macosx-arm64*.jar

  build-windows:
    runs-on: windows-2022

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt" # See 'Supported distributions' for available options
          java-version: "8"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Download SDL3
        run: curl -L -o SDL3.zip https://github.com/libsdl-org/SDL/releases/download/release-3.4.4/SDL3-devel-3.4.4-VC.zip

      - name: Unpack SDL3
        shell: bash
        run: |
          mkdir -p "${{ runner.temp }}/SDL3"
          mkdir -p "${{ runner.temp }}/ziptmp"
          unzip SDL3.zip -d "${{ runner.temp }}/ziptmp"
          mv "${{ runner.temp }}/ziptmp"/*/* "${{ runner.temp }}/SDL3"

      - name: Set SDL3_DIR environment variable
        run: echo SDL3_DIR=${{ runner.temp }}\SDL3\cmake >> $env:GITHUB_ENV

      - name: Build raylib
        run: |
          cd raylib
          mkdir build
          cd build
          cmake -DPLATFORM="SDL" -DOPENGL_VERSION="3.3" -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DSUPPORT_BUSY_WAIT_LOOP=OFF -DSUPPORT_CUSTOM_FRAME_CONTROL=OFF -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
          msbuild raylib.sln /target:raylib /property:Configuration=Release
          copy raylib\Release\raylib.lib ..\..
          cd ..\..
        shell: cmd

      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: windows-x86_64
        run: |
          build-windows.bat
        shell: cmd

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jaylib-windows-x86_64
          path: ./jaylib-natives*.jar

  build-windows32:
    runs-on: windows-2022

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-java@v2
        with:
          distribution: "adopt" # See 'Supported distributions' for available options
          java-version: "8"
          architecture: "x86"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86

      - name: Build raylib
        run: |
          cd raylib
          mkdir build
          cd build
          cmake -A Win32 -DBUILD_EXAMPLES=OFF -DCUSTOMIZE_BUILD=ON -DOPENGL_VERSION=2.1 -DSUPPORT_FILEFORMAT_JPG=ON -DSUPPORT_FILEFORMAT_FLAC=ON -DWITH_PIC=ON -DCMAKE_BUILD_TYPE=Release ..
          msbuild raylib.sln /target:raylib /property:Configuration=Release
          copy raylib\Release\raylib.lib ..\..
          cd ..\..
        shell: cmd

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Build jaylib
        env:
          RAYLIB_PLATFORM: windows-x86
        run: |
          build-windows.bat
        shell: cmd

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: jaylib-windows-x86
          path: ./jaylib-natives*.jar

  merge-artifacts:
    runs-on: ubuntu-latest
    needs:
      [
        build-linux,
        build-linux-32bit,
        build-linux-arm64,
        build-mac,
        build-windows,
        build-windows32,
      ]

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Upload merged artifact
        uses: actions/upload-artifact@v4
        with:
          name: jaylib-all-platforms
          path: artifacts/
